#!/bin/bash

# userisonnodes
#
# query pbs to see what nodes a user is running on
#
# Original written by Brett Pemberton, brett@vpac.org
# Modified by Craig West, cwest@vpac.org
# Copyright (C) 2013 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

CONFIG=/usr/local/recluse/config
[ -r "$CONFIG" ] || echo "Can't source $CONFIG"
[ -r "$CONFIG" ] || exit 0
source $CONFIG

user=$1

if [ $# -ne 1 ]
then
	echo "usage: $0 <user>"
	exit 1
fi

for node in $(mdiag -j --xml $1 | sed -e "s/^.*AllocNodeList=\"//g" | sed -e "s/\".*$//g" | sed -e "s/,/ /g")
do
	echo $node | sed "s/.*\($cluster[0-9][0-9][0-9]\).*/\1/"
done 
