#!/bin/bash

# nodejobs
#
# query torque (PBS) to find out a list of jobs on the node
#
# Written by Craig West, cwest@vpac.org
# Copyright (C) 2013 Victorian Partnership for Advanced Computing

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

/usr/local/sbin/momctl -q jobs | awk -F "'" '{print $2}' | sed -e "s/^jobs=//"
